package client

import (
	"context"
	"crypto/rand"
	"crypto/tls"
	"encoding/hex"
	"errors"
	"fmt"
	"sync"
	"sync/atomic"
	"time"

	"github.com/mtingers/dflockd/internal/protocol"
)

// ErrTooManyRedirects is returned when a Cluster operation exhausted
// its attempt budget without finding the leader. The returned error
// also wraps the final dial or NotLeaderError cause for diagnostics.
// This bounds an attacker-controlled redirect loop and a long partition.
var ErrTooManyRedirects = errors.New("dflockd: too many leader redirects")

// ErrNoMembers is returned by NewCluster when the members slice is
// empty. At least one member is required to bootstrap the leader hunt.
var ErrNoMembers = errors.New("dflockd: cluster: no members configured")

var (
	ErrClusterClosed    = errors.New("dflockd: cluster client is closed")
	ErrInvalidStableRef = errors.New("dflockd: invalid cluster stable ref")
)

// defaultRedirectBudget bounds the total number of dial+op attempts
// per Cluster operation. With 3 it allows: 1 to the cached leader,
// then 1 each to the two other members of a typical 3-node cluster.
const defaultRedirectBudget = 3

// dialFunc is the context-aware connection factory. Tests inject a fake.
type dialFunc func(context.Context, string) (*Conn, error)

// clusterCfg is the resolved set of options for a Cluster.
type clusterCfg struct {
	budget    int
	dial      dialFunc
	authToken string
	stableRef string
	optionErr error
	tlsConfig *tls.Config
}

// ClusterOption configures NewCluster.
type ClusterOption func(*clusterCfg)

// WithClusterRedirectBudget caps the consecutive dial+op attempts a
// single Cluster operation may make before returning
// ErrTooManyRedirects. Default 3.
func WithClusterRedirectBudget(n int) ClusterOption {
	return func(c *clusterCfg) {
		if n > 0 {
			c.budget = n
		}
	}
}

// WithClusterAuthToken makes every dialed Conn authenticate with the
// given session token before the first operation. Empty token means
// no authentication step (the default).
func WithClusterAuthToken(tok string) ClusterOption {
	return func(c *clusterCfg) { c.authToken = tok }
}

// WithClusterStableRef replaces the random stable identity generated by
// NewCluster. Every dialed Conn sends a `stable-ref` command before the
// first operation. With a stable ref set,
// a Cluster operation's underlying acquire/enqueue/wait carries this
// identity across a leader failover — a reconnect re-attaches to the
// existing FSM slot (preserving FIFO position) rather than starting
// from the back of the queue.
//
// ref must be non-empty and at most 64 printable ASCII bytes. Invalid input
// makes NewCluster return ErrInvalidStableRef.
//
// A ref names one client session, shared by both of the Cluster's lanes;
// independent workers should still use independent Cluster values and refs.
// Refs are unauthenticated identifiers, so generate them randomly and treat
// them like session tokens.
func WithClusterStableRef(ref string) ClusterOption {
	return func(c *clusterCfg) {
		if err := protocol.ValidateStableRef(ref); err != nil {
			c.optionErr = fmt.Errorf("%w: %v", ErrInvalidStableRef, err)
			return
		}
		c.stableRef = ref
	}
}

// WithClusterTLS enables TLS for every member connection. The configuration is
// cloned at construction so later caller mutation cannot race active dials.
func WithClusterTLS(cfg *tls.Config) ClusterOption {
	return func(c *clusterCfg) {
		if cfg == nil {
			c.optionErr = errors.New("dflockd: cluster TLS config is nil")
			return
		}
		c.tlsConfig = cfg.Clone()
	}
}

// withClusterDial is an internal option used by tests to inject a
// fake dialer. Not exported.
func withClusterDial(d dialFunc) ClusterOption {
	return func(c *clusterCfg) { c.dial = d }
}

// Cluster is a failover-aware dflockd client. It keeps a process-local
// leader hint, reuses its connections, and follows redirects or transport
// failures through known members up to the configured budget.
//
// Cluster is safe for concurrent use. It owns one logical session, identified
// by a single stable ref, carried over two connections:
//
//   - the session lane runs the operations that block for a grant (acquire,
//     enqueue, wait). Enqueue and its matching Wait share this lane because
//     the server keys pending-grant state by connection.
//   - the control lane runs the token-authorized lifecycle calls (release,
//     renew) and barrier. These are bounded by the server's read timeout.
//
// Splitting them is what lets a caller renew a lease it already holds while
// another call is parked waiting for a different key; a single shared
// connection would queue the renew behind the blocked acquire until the lease
// expired. Both lanes send the same stable ref, which is safe because the
// server scopes disconnect cleanup by connection ID, not by ref.
//
// Two consequences worth knowing:
//
//   - a Cluster opens up to two connections, so per-client connection limits
//     (--max-conns, --max-conns-per-ip) should allow for that.
//   - renewing a lease rebinds its holder to the control lane, so after the
//     first successful Renew it is the control lane's disconnect — not the
//     session lane's — that auto-releases that lock.
//
// Concurrent blocking calls (two acquires at once) still serialize on the
// session lane; give independent workers independent Cluster values.
type Cluster struct {
	members []string
	cfg     clusterCfg
	leader  atomic.Pointer[string]

	session clusterLane
	control clusterLane
	closed  atomic.Bool
}

// clusterLane is one persistent connection plus the lock that serializes the
// request/response exchanges on it. The wire protocol has no request IDs, so
// exactly one operation may be in flight per connection.
type clusterLane struct {
	mu       sync.Mutex
	conn     *Conn
	connAddr string
}

// NewCluster returns a failover-aware client over the given member
// list. Members are client-facing host:port pairs for every node in
// the cluster (the same value each node was started with as
// --advertise-addr, or --host:--port if unset). At least one member
// is required.
func NewCluster(members []string, opts ...ClusterOption) (*Cluster, error) {
	if len(members) == 0 {
		return nil, ErrNoMembers
	}
	cfg := clusterCfg{budget: defaultRedirectBudget}
	for _, opt := range opts {
		opt(&cfg)
	}
	if cfg.optionErr != nil {
		return nil, cfg.optionErr
	}
	if cfg.stableRef == "" {
		ref, err := randomClusterStableRef()
		if err != nil {
			return nil, err
		}
		cfg.stableRef = ref
	}
	if cfg.dial == nil {
		if cfg.tlsConfig != nil {
			tlsConfig := cfg.tlsConfig
			cfg.dial = func(ctx context.Context, addr string) (*Conn, error) {
				return dialTLSContext(ctx, addr, tlsConfig)
			}
		} else {
			cfg.dial = dialContext
		}
	}
	mem := make([]string, len(members))
	copy(mem, members)
	return &Cluster{members: mem, cfg: cfg}, nil
}

func randomClusterStableRef() (string, error) {
	var raw [16]byte
	if _, err := rand.Read(raw[:]); err != nil {
		return "", fmt.Errorf("dflockd: generate cluster stable ref: %w", err)
	}
	var encoded [32]byte
	hex.Encode(encoded[:], raw[:])
	return string(encoded[:]), nil
}

// LeaderHint returns the current leader cache (empty if none has
// been observed). Exposed for diagnostics — production callers
// should not depend on this returning the truly-current leader.
func (cl *Cluster) LeaderHint() string {
	p := cl.leader.Load()
	if p == nil {
		return ""
	}
	return *p
}

// dispatch dials a member (preferring the leader cache) and runs op
// against it. On *NotLeaderError it records the hint (only if the
// hinted address is in the operator-supplied members list — an
// attacker-controlled server cannot point us at an arbitrary host)
// and retries against the new target. Returns an error wrapping both
// ErrTooManyRedirects and the final dial/redirect cause once the budget
// is exhausted.
// dispatchSession runs op on the lane reserved for calls that block for a
// grant. Enqueue and its matching Wait must both land here.
func (cl *Cluster) dispatchSession(ctx context.Context, op func(c *Conn) error) error {
	return cl.dispatch(ctx, &cl.session, op)
}

// dispatchControl runs op on the lane reserved for token-authorized lifecycle
// calls and barrier, so they cannot queue behind a blocked acquire or wait.
func (cl *Cluster) dispatchControl(ctx context.Context, op func(c *Conn) error) error {
	return cl.dispatch(ctx, &cl.control, op)
}

func (cl *Cluster) dispatch(ctx context.Context, lane *clusterLane, op func(c *Conn) error) error {
	lane.mu.Lock()
	defer lane.mu.Unlock()
	if cl.closed.Load() {
		return ErrClusterClosed
	}
	addr := cl.firstAddr()
	var lastErr error
	for attempt := 0; attempt < cl.cfg.budget; attempt++ {
		if err := ctx.Err(); err != nil {
			return err
		}
		next, final, err := cl.attemptOnce(ctx, lane, addr, op)
		if final {
			return err
		}
		lastErr, addr = err, next
	}
	return budgetExhausted(lastErr)
}

// attemptOnce runs one dial-then-operate cycle against addr. final reports
// that err is the caller's answer; otherwise err is the cause to remember and
// next is the address the following attempt should use.
func (cl *Cluster) attemptOnce(
	ctx context.Context, lane *clusterLane, addr string, op func(c *Conn) error,
) (next string, final bool, err error) {
	conn, dialErr := cl.connection(ctx, lane, addr)
	if dialErr != nil {
		if ctxErr := ctx.Err(); ctxErr != nil {
			return "", true, ctxErr
		}
		return cl.nextAddr(addr), false, fmt.Errorf("dflockd: cluster: dial %s: %w", addr, dialErr)
	}
	opErr := cl.runOnConn(ctx, lane, conn, op)
	if redirected, target := redirectTarget(opErr); redirected {
		lane.dropConnection()
		return cl.redirectAddr(target, addr), false, opErr
	}
	if opErr != nil && !connectionReusableAfter(opErr) {
		if ctxErr := ctx.Err(); ctxErr != nil {
			return "", true, ctxErr
		}
		lane.dropConnection()
		return cl.nextAddr(addr), false, fmt.Errorf("dflockd: cluster: operation on %s: %w", addr, opErr)
	}
	if opErr == nil {
		cl.updateLeaderHint(addr)
	}
	return "", true, opErr
}

// redirectAddr picks where to go after a *NotLeaderError: the hinted leader
// when it names a known member we are not already talking to, else the next
// configured member.
func (cl *Cluster) redirectAddr(target, current string) string {
	if cl.updateLeaderHint(target) && target != current {
		return target
	}
	return cl.nextAddr(current)
}

func budgetExhausted(lastErr error) error {
	if lastErr == nil {
		return ErrTooManyRedirects
	}
	return fmt.Errorf("%w: last attempt: %w", ErrTooManyRedirects, lastErr)
}

func (cl *Cluster) connection(ctx context.Context, lane *clusterLane, addr string) (*Conn, error) {
	if lane.conn != nil && lane.connAddr == addr {
		return lane.conn, nil
	}
	lane.dropConnection()
	conn, err := cl.cfg.dial(ctx, addr)
	if err != nil {
		return nil, err
	}
	if cl.cfg.authToken != "" {
		if err := Authenticate(conn, cl.cfg.authToken); err != nil {
			conn.Close()
			return nil, err
		}
	}
	if cl.cfg.stableRef != "" {
		if err := SetStableRef(conn, cl.cfg.stableRef); err != nil {
			conn.Close()
			return nil, err
		}
	}
	lane.conn, lane.connAddr = conn, addr
	return conn, nil
}

func (lane *clusterLane) dropConnection() {
	if lane.conn != nil {
		_ = lane.conn.Close()
	}
	lane.conn, lane.connAddr = nil, ""
}

func (lane *clusterLane) close() error {
	lane.mu.Lock()
	defer lane.mu.Unlock()
	var err error
	if lane.conn != nil {
		err = lane.conn.Close()
	}
	lane.conn, lane.connAddr = nil, ""
	return err
}

// Close ends the logical session and closes both lanes. Idempotent.
func (cl *Cluster) Close() error {
	if !cl.closed.CompareAndSwap(false, true) {
		return nil
	}
	sessErr := cl.session.close()
	ctrlErr := cl.control.close()
	if sessErr != nil {
		return sessErr
	}
	return ctrlErr
}

// updateLeaderHint records a hint only if it names an address in the
// operator-supplied members list. An attacker-controlled response
// pointing at `evil.example.com:6388` is rejected — we'll keep
// rotating through the known members instead. The return reports
// whether target was accepted.
func (cl *Cluster) updateLeaderHint(target string) bool {
	if target == "" || !cl.isKnownMember(target) {
		cl.leader.Store(nil)
		return false
	}
	cl.leader.Store(&target)
	return true
}

// isKnownMember reports whether addr appears in the configured
// members list.
func (cl *Cluster) isKnownMember(addr string) bool {
	for _, m := range cl.members {
		if m == addr {
			return true
		}
	}
	return false
}

// runOnConn binds context cancellation to the current operation. The
// connection remains open after success so later lifecycle calls share the
// same server-side session.
func (cl *Cluster) runOnConn(ctx context.Context, lane *clusterLane, conn *Conn, op func(c *Conn) error) error {
	stopCancel := closeConnOnContextDone(ctx, conn)
	stopped := false
	defer func() {
		if !stopped {
			stopCancel()
		}
	}()
	err := preferContextErr(ctx, op(conn))
	stopCancel()
	stopped = true
	if ctx.Err() != nil {
		lane.dropConnection()
	}
	return err
}

func connectionReusableAfter(err error) bool {
	return errors.Is(err, ErrTimeout) ||
		errors.Is(err, ErrMaxLocks) ||
		errors.Is(err, ErrMaxWaiters) ||
		errors.Is(err, ErrServer) ||
		errors.Is(err, ErrNotQueued) ||
		errors.Is(err, ErrAlreadyQueued) ||
		errors.Is(err, ErrLimitMismatch) ||
		errors.Is(err, ErrLeaseExpired) ||
		errors.Is(err, ErrAuth)
}

func preferContextErr(ctx context.Context, err error) error {
	if ctxErr := ctx.Err(); ctxErr != nil {
		return ctxErr
	}
	return err
}

// firstAddr picks the cached leader when available, otherwise the first
// configured member.
func (cl *Cluster) firstAddr() string {
	if hint := cl.LeaderHint(); hint != "" {
		return hint
	}
	return cl.members[0]
}

// nextAddr returns the configured member after current, wrapping at
// the end. An unknown current address restarts at the first member.
func (cl *Cluster) nextAddr(current string) string {
	for i, member := range cl.members {
		if member == current {
			return cl.members[(i+1)%len(cl.members)]
		}
	}
	return cl.members[0]
}

// redirectTarget reports whether err is a *NotLeaderError and, if so,
// the Leader field on it.
func redirectTarget(err error) (bool, string) {
	var nle *NotLeaderError
	if errors.As(err, &nle) {
		return true, nle.Leader
	}
	return false, ""
}

// Acquire is the cluster-aware Acquire.
func (cl *Cluster) Acquire(ctx context.Context, key string, timeout time.Duration, opts ...Option) (string, int, error) {
	var token string
	var ttl int
	err := cl.dispatchSession(ctx, func(c *Conn) error {
		t, l, e := Acquire(c, key, timeout, opts...)
		token, ttl = t, l
		return e
	})
	return token, ttl, err
}

// Release is the cluster-aware Release.
func (cl *Cluster) Release(ctx context.Context, key, token string) error {
	return cl.dispatchControl(ctx, func(c *Conn) error { return Release(c, key, token) })
}

// Renew is the cluster-aware Renew.
func (cl *Cluster) Renew(ctx context.Context, key, token string, opts ...Option) (int, error) {
	var remaining int
	err := cl.dispatchControl(ctx, func(c *Conn) error {
		r, e := Renew(c, key, token, opts...)
		remaining = r
		return e
	})
	return remaining, err
}

// Enqueue is the cluster-aware Enqueue.
func (cl *Cluster) Enqueue(ctx context.Context, key string, opts ...Option) (string, string, int, error) {
	var status, token string
	var ttl int
	err := cl.dispatchSession(ctx, func(c *Conn) error {
		s, t, l, e := Enqueue(c, key, opts...)
		status, token, ttl = s, t, l
		return e
	})
	return status, token, ttl, err
}

// Wait is the cluster-aware Wait.
func (cl *Cluster) Wait(ctx context.Context, key string, timeout time.Duration) (string, int, error) {
	var token string
	var ttl int
	err := cl.dispatchSession(ctx, func(c *Conn) error {
		t, l, e := Wait(c, key, timeout)
		token, ttl = t, l
		return e
	})
	return token, ttl, err
}

// SemAcquire is the cluster-aware SemAcquire.
func (cl *Cluster) SemAcquire(ctx context.Context, key string, timeout time.Duration, limit int, opts ...Option) (string, int, error) {
	var token string
	var ttl int
	err := cl.dispatchSession(ctx, func(c *Conn) error {
		t, l, e := SemAcquire(c, key, timeout, limit, opts...)
		token, ttl = t, l
		return e
	})
	return token, ttl, err
}

// SemRelease is the cluster-aware SemRelease.
func (cl *Cluster) SemRelease(ctx context.Context, key, token string) error {
	return cl.dispatchControl(ctx, func(c *Conn) error { return SemRelease(c, key, token) })
}

// SemRenew is the cluster-aware SemRenew.
func (cl *Cluster) SemRenew(ctx context.Context, key, token string, opts ...Option) (int, error) {
	var remaining int
	err := cl.dispatchControl(ctx, func(c *Conn) error {
		r, e := SemRenew(c, key, token, opts...)
		remaining = r
		return e
	})
	return remaining, err
}

// SemEnqueue is the cluster-aware SemEnqueue.
func (cl *Cluster) SemEnqueue(ctx context.Context, key string, limit int, opts ...Option) (string, string, int, error) {
	var status, token string
	var ttl int
	err := cl.dispatchSession(ctx, func(c *Conn) error {
		s, t, l, e := SemEnqueue(c, key, limit, opts...)
		status, token, ttl = s, t, l
		return e
	})
	return status, token, ttl, err
}

// SemWait is the cluster-aware SemWait.
func (cl *Cluster) SemWait(ctx context.Context, key string, timeout time.Duration) (string, int, error) {
	var token string
	var ttl int
	err := cl.dispatchSession(ctx, func(c *Conn) error {
		t, l, e := SemWait(c, key, timeout)
		token, ttl = t, l
		return e
	})
	return token, ttl, err
}

// Barrier is the cluster-aware Barrier. In cluster mode the returned
// nil means the leader's commit index has caught up to the latest
// proposal at call time; a subsequent read on the leader will reflect
// every preceding committed write.
func (cl *Cluster) Barrier(ctx context.Context) error {
	return cl.dispatchControl(ctx, func(c *Conn) error { return Barrier(c) })
}
